blogs/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'), # 목록
    path('<int:post_id>/', views.detail, name='detail'), #상세 페이지
    path('post/create/', views.post_create, name='post_create'),
    path('category/<str:slug>/', views.category_page,
            name='category_page'), # 카테고리별 페이지
    path('post/delete/<int:post_id>/', views.post_delete,
            name='post_delete'),  #포스트 삭제
    path('comment/create/<int:post_id>/', views.comment_create,
            name='comment_create'), #댓글 등록
    path('comment/delete/<int:comment_id>/', views.comment_delete,
            name='comment_delete'), #댓글 삭제
    path('comment/modify/<int:comment_id>/', views.comment_modify,
            name='comment_modify'), #댓글 수정
]

blogs/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index), #http://127.0.0.1:8000/
    path('blog/', include('blog.urls')),
    path('common/', include('common.urls')),  #일반 로그인
    path('accounts/', include('allauth.urls')), #소셜 로그인
]

urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

blogs/blog/models.py
import os

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# 카테고리 모델
class Category(models.Model):
    # unique=True 중복 불허
    name = models.CharField(max_length=50, unique=True)
    # url주소 - 문자, allow_unicode - 한글허용
    slug = models.SlugField(max_length=200, unique=True,
                allow_unicode=True)

    def __str__(self):
        return self.name

    # 카테고리 url 주소
    def get_absolute_url(self):
        # return f'/blog/category/{self.slug}'  #절대 경로
        # reverse() - redirect 유사 : app-name으로 경로 이동
        return reverse('blog:category_page', args=[self.slug])

    # 관리자 페이지에서 적용 - verbose_name_plural(복수형)
    class Meta:
        ordering = ['name']  # 이름순 정렬
        verbose_name = 'category'
        verbose_name_plural = 'categories'

# 포스트 모델
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)  #제목
    content = models.TextField()              #내용
    pub_date = models.DateTimeField()         #발행일
    modify_date = models.DateTimeField(null=True, blank=True) #입력 폼이 비어도 됨
    photo = models.ImageField(upload_to='blog/images/%Y/%m/%d/',
                    null=True, blank=True)  #null 허용, 파일을 첨부하지 않을수 있음
    file = models.FileField(upload_to='blog/files/%Y/%m/%d/',
                    null=True, blank=True)
    # models.SET_NULL: 카테고리가 삭제되어도 카테고리가 없는 포스트는 유지
    category = models.ForeignKey(Category, null=True, blank=True,
                    on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

    # 파일의 이름 출력
    def get_file_name(self):
        return os.path.basename(self.file.name)

    # 파일의 확장자 구분
    def get_file_ext(self):
        # seoul.csv ->split() -> [seoul, csv]
        return self.get_file_name().split('.')[-1]

# 댓글 모델
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    pub_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    #게시글이 부모키(기본키), 댓글이 자식키(외래키)
    post = models.ForeignKey(Post, null=True, blank=True,
                    on_delete=models.CASCADE)

blogs/blog/forms.py
from django import forms
from blog.models import Post, Comment

# 포스트 폼 생성
class PostForm(forms.ModelForm):
    class Meta:
        model = Post  #Post 객체 생성
        fields = ['title', 'content', 'photo', 'file', 'category']
        labels = {
            'title': '제목',
            'content': '내용',
            'photo': '사진',
            'file': '파일',
            'category': '분류'
        }

# 댓글 폼
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {'content': '댓글 내용'}

blogs/blog/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect
from django.utils import timezone

from blog.forms import PostForm, CommentForm
from blog.models import Post, Category, Comment

def index(request):
    #최신글 3개 보내기
    new_post = Post.objects.order_by('-pub_date')[0:3]
    context = {'new_post': new_post,}
    return render(request, 'blog/index.html', context)

# 포스트 목록
def post_list(request):
    post_list = Post.objects.order_by('-pub_date') # 포스트 전체 검색
    categories = Category.objects.all() #카테고리 전체 검색

    #게시글 총 개수
    total_post = len(post_list)

    #검색 처리
    kw = request.GET.get('kw', '')  #입력폼의 넘어온 키워드
    if kw:
        post_list = post_list.filter(
            Q(title__icontains=kw) |   #제목 검색
            Q(content__icontains=kw) | #내용 검색
            Q(author__username__icontains=kw) #글쓴이 검색
        ).distinct()

    # 페이지 처리
    page = request.GET.get('page', 1)
    paginator = Paginator(post_list, 5)  # 페이당 포스트 개수 - 5
    page_obj = paginator.get_page(page)

    context = {
        'post_list': page_obj,
        'categories': categories,
        'total_post': total_post,
        'kw': kw
    }
    return render(request, 'blog/post_list.html', context)

# 상세 페이지
def detail(request, post_id):
    post = Post.objects.get(id=post_id)
    categories = Category.objects.all()  # 카테고리 전체 검색

    post_list = Post.objects.all()
    # 게시글 총 개수
    total_post = len(post_list)

    context = {
        'post': post,
        'categories': categories,
        'total_post': total_post
    }
    return render(request, 'blog/detail.html', context)

# 글쓰기
@login_required(login_url='common:login')
def post_create(request):
    categories = Category.objects.all()  #전테 카테고리 가져옴
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES) #(일반속성, 파일)
        if form.is_valid(): #유효하다면
            post = form.save(commit=False)
            post.pub_date = timezone.now()  # 현재 시간
            post.author = request.user  #로그인한 사람이 글쓴이임
            post.save()
            return redirect('blog:post_list')
    else:
        form = PostForm()  #비어있는 폼
    context = {'form': form, 'categories': categories}
    return render(request, 'blog/post_form.html', context)

# 카테고리별 페이지 처리 메서드
def category_page(request, slug):
    current_category = Category.objects.get(slug=slug) #현재 카테고리 검색
    post_list = Post.objects.filter(category=current_category) # 현 카테고리의 포스트들
    post_list = post_list.order_by('-pub_date')  #날짜순 내림차순
    categories = Category.objects.all() #전체 카테고리

    all_post_list = Post.objects.all()  # 전체 게시글 목록
    total_post = len(all_post_list)     # 게시글 총 개수

    # 검색 처리
    kw = request.GET.get('kw', '')  # 입력폼의 넘어온 키워드
    if kw:
        post_list = post_list.filter(
            Q(title__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(author__username__icontains=kw)  # 글쓴이 검색
        ).distinct()

    # 페이지 처리
    page = request.GET.get('page', 1)
    paginator = Paginator(post_list, 5)  # 페이당 포스트 개수 - 5
    page_obj = paginator.get_page(page)

    context = {
        'current_category': current_category,
        'post_list': page_obj,
        'categories': categories,
        'total_post': total_post,
        'kw': kw
    }
    return render(request, 'blog/post_list.html', context)

@login_required(login_url='common:login')
def post_delete(request, post_id):
    post = Post.objects.get(id=post_id)  #삭제할 포스트
    post.delete()
    return redirect('blog:post_list')

# 댓글 등록
@login_required(login_url='common:login')
def comment_create(request, post_id):
    post = Post.objects.get(id=post_id)  # 댓글 쓰기위한 포스트 1개 가져옴
    if request.method == "POST":
        form = CommentForm(request.POST)  # 입력된 댓글 가져옴
        if form.is_valid():
            comment = form.save(commit=False) #가저장(content)
            comment.author = request.user  #로그인한 글쓴이
            comment.pub_date = timezone.now()  # 작성일
            comment.post = post
            form.save()  #실제 저장 - db에 저장
    return redirect('blog:detail', post_id=post_id)

# 댓글 삭제
@login_required(login_url='common:login')
def comment_delete(request, comment_id):
    #삭제할 댓글 1개 가져오기
    comment = Comment.objects.get(id=comment_id)
    comment.delete()  # 댓글 삭제 처리
    return redirect('blog:detail', post_id=comment.post_id)

# 댓글 수정
@login_required(login_url='common:login')
def comment_modify(request, comment_id):
    # 수정할 댓글 1개 가져오기
    comment = Comment.objects.get(id=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment) #수정한 내용 가져옴
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()  #수정한 날짜 및 시간
            comment.save() #실저장
            return redirect('blog:detail', post_id=comment.post_id)
    else:
        form = CommentForm(instance=comment)  #댓글에 입력된 내용
    context = {'form': form}
    return render(request, 'blog/comment_form.html', context)

blogs/templates/blog/comment_form.html
{% extends 'base.html' %}
{% block title %}
  댓글 수정
{% endblock %}
{% block content %}
<form action="" method="post">
  {% csrf_token %}
  {% include 'form_errors.html' %}
  <div class="form-group">
    <label for="content">댓글 내용</label>
    <textarea name="content" id="content" rows="3"
              class="form-control my-3">{{ form.content.value }}</textarea>
  </div>
  <button type="submit" class="btn btn-primary">저장하기</button>
</form>
{% endblock %}

blogs/templates/blog/detail.html
{% extends 'base.html' %}
{% block title %}포스트 상세 내용입니다.
{% endblock %}
{% block content %}
    {% if post.category %}
        <h6 class="text-end">[{{ post.category }}]</h6>
    {% endif %}
    <h3>{{ post.title }}</h3>
    <h5 style="white-space: pre-line; line-height: 1.5">
        {{ post.content }}
    </h5>
    <p>글쓴이: {{ post.author }} (작성일: {{ post.pub_date }})</p>
    <!-- 이미지 파일이 있으면 보이기 -->
    {% if post.photo %}
        <img src="{{ post.photo.url }}">
    {% endif %}
    <!-- 파일이 있으면 보이기 -->
    {% if post.file %}
    <p>
        <a href="{{ post.file.url }}" class="btn btn-outline-dark">
            Download:
            {% if post.get_file_ext == 'csv' %}
                <i class="fa-solid fa-file-csv"></i>
            {% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                <i class="fa-solid fa-file-excel"></i>
            {% else %}
                <i class="fa-solid fa-file"></i>
            {% endif %}
        {{ post.get_file_name }}</a>
    </p>
    {% endif %}

    <!-- 댓글 영역 -->
    <div class="mt-3">
        <h5><i class="fa-solid fa-pen-to-square"></i> 댓글</h5>
        {% for comment in post.comment_set.all %}
        <div class="comment text-muted">
            <span>{{ comment.content|linebreaks }}</span>
            <span>-{{ comment.author }}, {{ comment.pub_date }}
                <!-- 수정일 추가 표시 -->
                {% if comment.modify_date %}
                (수정일: {{ comment.modify_date }})
                {% endif %}
            </span>
            <!-- 댓글 수정, 삭제 -->
            {% if comment.author == request.user %}
                <a href="{% url 'blog:comment_modify' comment.id %}">수정</a>
                <a href="#" class="delete"
                   data-uri="{% url 'blog:comment_delete' comment.id %}">삭제</a>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    <!-- 댓글 등록 폼 -->
    <div>
        <form action="{% url 'blog:comment_create' post.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <textarea name="content" rows="3"
                          placeholder="댓글을 남겨보세요"
                          class="form-control my-3"></textarea>
                <button type="submit"
                        class="btn btn-sm btn-outline-success">등록</button>
            </div>
        </form>
    </div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function(){
        //삭제 처리
        $(".delete").click(function(){
            if(confirm('정말로 삭제하시겠습니까?')){
                location.href=$(this).data('uri');
            }
        });
    });
</script>
{% endblock %}

blogs/templates/blog/index.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>환영합니다...</title>
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <script src="{% static 'blog/js/bootstrap.js' %}"></script>
    <script src="https://kit.fontawesome.com/187dabceeb.js"
            crossorigin="anonymous"></script> <!-- fontawesome 키트-->
</head>
<body>
{% include 'navbar.html' %}
<!-- 본문 영역 -->
<div class="container my-3">
    <div class="row">
        <div class="col-8">
           <h2 class="text-center">MyBlog - 일상의 기록</h2>
            <div class="my-4 text-center">
                <img class="rounded-2"
                    src="{% static 'blog/images/activity.jpg' %}" alt="패러글라이딩">
                <!-- 최신글 보이기 -->
                <div class="row">
                    <div class="col-2"></div>
                    <div class="col-8 text-start">
                        <h5 class="mt-4 px-2">최근 포스트</h5>
                        <div class="card">
                            <div class="card-body">
                                {% for post in new_post %}
                                    <p>
                                        <a href="{% url 'blog:detail' post.id %}">
                                            {{ post.title }} -
                                            ({{ post.author }}, {{ post.pub_date}})
                                        </a>
                                    </p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> <!--col-8 끝 -->
    </div><!--row 끝 -->
</div> <!--container 끝 -->
</body>
</html>

blogs/templates/blog/post_form.html
{% extends 'base.html' %}
{% block title %}글쓰기 폼입니다.
{% endblock %}
{% block content %}
<h3>글쓰기</h3>
<form action="" method="post"
      enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'form_errors.html' %}
    <!--{{ form.as_p }}-->
    <div class="form-group my-2">
          <label for="title" class="mb-1">제목</label>
          <input type="text" id="title" name="title"
                 class="form-control my-2"
                 value="{{ form.title.value|default_if_none:'' }}">
    </div>
    <div class="form-group my-2">
          <label for="content" class="mb-1">내용</label>
          <textarea name="content" id="content" rows="7"
                    class="form-control my-2">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <div class="form-group my-2">
          <label for="photo" class="mb-1">사진</label>
          <input type="file" id="photo" name="photo"
                 class="form-control my-2"
                 value="{{ form.photo.value|default_if_none:'' }}">
    </div>
    <div class="form-group my-2">
          <label for="file" class="mb-1">파일</label>
          <input type="file" id="file" name="file"
                 class="form-control my-2"
                 value="{{ form.file.value|default_if_none:'' }}">
    </div>
    <div class="form-group my-2">
          <label for="category" class="mb-1">분류</label>
          <select name="category" id="category" class="form-select">
              <!-- value값은 category의 id를 사용 -->
              {% for category in categories %}
              <option value="{{ category.id }}">{{ category.name }}</option>
              {% endfor %}
          </select>
    </div>
    <button type="submit" class="btn btn-primary mt-4">저장하기</button>
</form>
{% endblock %}

blogs/templates/blog/post_list.html
{% extends 'base.html' %}
{% block title %}포스트 목록입니다.
{% endblock %}
{% block content %}
    <h2>Blog 홈</h2>
    {% if post_list %}
        <!-- 포스트 가져옴 -->
        {% for post in post_list %}
            <hr>
            {% if post.category %}
                <h6 class="text-end">[{{ post.category }}]</h6>
            {% endif %}
            <h3 class="my-3">
                <a href="{% url 'blog:detail' post.id %}">
                    {{ post.title }}
                </a>
            </h3>
            <h5 style="white-space: pre-line; line-height: 1.5">
                {{ post.content }}
            </h5>
            <p>글쓴이: {{ post.author }} (작성일: {{ post.pub_date }})
                <!-- 로그인한 사용자와 글쓴이가 일치하면 삭제가 보임 -->
                {% if post.author == request.user %}
                <a href="#" class="delete"
                   data-uri="{% url 'blog:post_delete' post.id %}"> | 삭제</a>
                {% endif %}
            </p>
            {% if post.photo %}
                <img src="{{ post.photo.url }}">
            {% endif %}
        {% endfor %}
    {% else %}
        <p>포스트가 없습니다.</p>
    {% endif %}

    <!-- 페이지 처리 영역-->
    <div class="row my-3">
        <ul class="pagination justify-content-center">
            <!-- 이전 페이지 -->
            {% if post_list.has_previous %}
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ post_list.previous_page_number }}">&laquo;</a>
                </li>
            {% else %}
                <!-- 이전 페이지가 없어도 표시됨 -->
                <li class="page-item disabled">
                    <a class="page-link" href="">&laquo;</a>
                </li>
            {% endif %}
            <!-- 현재 페이지 -->
            {% for page_number in post_list.paginator.page_range %}
                <!-- 현재 페이지와 리스트의 페이지가 일치하면 활성화함-->
                {% if page_number == post_list.number %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ page_number }}">
                        {{ page_number }}
                    </a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">
                        {{ page_number }}
                    </a>
                </li>
                {% endif %}
            {% endfor %}
            <!-- 다음 페이지 -->
            {% if post_list.has_next %}
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ post_list.next_page_number }}">&raquo;</a>
                </li>
            {% else %}
                <!-- 이전 페이지가 없어도 표시됨 -->
                <li class="page-item disabled">
                    <a class="page-link" href="">&raquo;</a>
                </li>
            {% endif %}
        </ul>
    </div>
    <!-- 페이지 처리 끝-->
    <!-- 검색 폼 : get 방식임-->
    <form action="" method="get" id="searchForm">
        {% csrf_token %}
        <input type="hidden" id="kw" name="kw" value="{{ kw }}">
    </form>
{% endblock %}

{% block script %}
<script>
    $(function(){
        //삭제 처리
        <!-- 링크 클릭 이벤트 -->
        $('.delete').click(function(){
            if(confirm('포스트를 정말 삭제하시겠습니까')){
                location.href=$(this).data('uri');  //클릭하면 해당 경로로 페이지이동
            }
        });

        //검색 처리
        //버튼 클릭 이벤트
        $('#btn_search').click(function(){
            $('#kw').val($('.kw').val());  //입력폼의 키워드를 가져와서 hidden 설정
            $('#searchForm').submit();     //검색폼을 전송함
        });
    });
</script>
{% endblock %}