blogs/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'), # 목록
    path('<int:post_id>/', views.detail, name='detail'), #상세 페이지
    path('post/create/', views.post_create, name='post_create'),
    path('category/<str:slug>/', views.category_page,
            name='category_page'), # 카테고리별 페이지
    path('post/delete/<int:post_id>/', views.post_delete,
            name='post_delete'),  #포스트 삭제
    path('comment/create/<int:post_id>/', views.comment_create,
            name='comment_create'), #댓글 등록
    path('comment/delete/<int:comment_id>/', views.comment_delete,
            name='comment_delete'), #댓글 삭제
    path('comment/modify/<int:comment_id>/', views.comment_modify,
            name='comment_modify'), #댓글 수정
]

blogs/common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html')
          , name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

blogs/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index), #http://127.0.0.1:8000/
    path('blog/', include('blog.urls')),
    path('common/', include('common.urls')),  #일반 로그인
    path('accounts/', include('allauth.urls')), #소셜 로그인
]

urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

blogs/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <script src="{% static 'blog/js/bootstrap.js' %}"></script>
    <script src="https://kit.fontawesome.com/187dabceeb.js"
            crossorigin="anonymous"></script> <!-- fontawesome 키트-->
    <!-- 제이 쿼리 -->
    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
</head>
<body>
{% include 'navbar.html' %}
<!-- 본문 영역 -->
<div class="container my-3">
    <div class="row">
        <div class="col-8">
            {% block content %}
            {% endblock %}
        </div>

        <!-- 검색 및 분류 -->
        <div class="col-4 col-lg-3">
            <!-- 검색 위젯 -->
            <div class="card my-3">
                <h5 class="card-header">Search</h5>
                <div class="card-body">
                    <div class="input-group">
                        <input type="text" class="kw form-control"
                                value="{{ kw }}">
                        <div class="input-group-append mx-1">
                            <button type="button" id="btn_search"
                                class="btn btn-outline-secondary">찾기</button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- 카테고리 위젯 -->
            <div class="card my-3">
                <h5 class="card-header">분류(Category)</h5>
                <div class="card-body">
                    <ul>
                        <li>
                            <a href="{% url 'blog:post_list' %}">
                                {% if not current_category %}
                                    <b>전체보기({{ total_post }})</b>
                                {% else %}
                                    전체보기({{ total_post }})
                                {% endif %}
                            </a>
                        </li>
                        {% for category in categories %}
                            {% if current_category.slug == category.slug %}
                           <!--category.post_set.count : 해당 포스트의 총 개수-->
                            <li style="background: #ff0">
                                <a href="{{ category.get_absolute_url }}">
                                {{ category.name }}({{ category.post_set.count }})
                                </a>
                            </li>
                            {% else %}
                            <li>
                                <a href="{{ category.get_absolute_url }}">
                                {{ category.name }}({{ category.post_set.count }})
                                </a>
                            </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div> <!-- card 끝 -->
        </div> <!-- 검색 및 분류 끝 -->
    </div> <!-- row 끝 -->
</div> <!-- container 끝 -->

<!-- 자바 스크립트 영역 -->
{% block script %}
{% endblock %}
</body>
</html>

blogs/templates/navbar.html
<!-- 소셜 로그인 태그 명시 -->
{% load socialaccount %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/">PyBlog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarNavDropdown">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_list' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post_create' %}">글쓰기</a>
        </li>
      </ul>
      <!-- 로그인 영역 -->
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
               data-bs-toggle="dropdown">{{ user.username }}</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'common:logout' %}">로그아웃</a>
            </div>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="#" data-bs-target="#loginModal"
               data-bs-toggle="modal">로그인</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<!-- 로그인 Modal -->
<div class="modal" tabindex="-1" id="loginModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          <i class="fa-solid fa-right-to-bracket"></i> Log In</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"
                aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <a href="{% provider_login_url 'google' %}"
           class="btn btn-outline-dark btn-block btn-sm mx-4">
          <i class="fa-brands fa-google"></i> Log in with Google
        </a>
        <a href="{% url 'common:login' %}"
           class="btn btn-outline-dark btn-block btn-sm">
          <i class="fa-solid fa-user"></i> Log in with ID
        </a>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary"
                data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>